name: "Manual"
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEBUG: 1
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
      VM_RELEASE: ${{ secrets.VM_RELEASE }}
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8000
    - name: Run vnc tunnel
      id: test
      uses: vmactions/ngrok-tunnel@v0.0.1
      with:
        protocol: tcp
        port: 5900
    - name: Sleep
      run: |
        for i in $(seq 1 10) ; do echo $i; sleep 1; done
        touch /tmp/keepalive
        echo "====================================="
        echo "please loin the SSH bellow, and run: "
        echo "bash run.sh importVM"
        echo "bash run.sh onBeforeStartVM "
        echo "bash run.sh startVM "
        echo "====================================="

    - uses: neilpang/debugger-action@master







